document.addEventListener('DOMContentLoaded',()=>{
 const theme=document.createElement('link');theme.rel='stylesheet';theme.href='imperial.css';document.head.appendChild(theme);
 const ryoryo=document.createElement('link');ryoryo.rel='stylesheet';ryoryo.href='ryoryo.css';document.head.appendChild(ryoryo);
 const archiveFix=document.createElement('link');archiveFix.rel='stylesheet';archiveFix.href='archive-fix.css';document.head.appendChild(archiveFix);
 const reportStyle=document.createElement('link');reportStyle.rel='stylesheet';reportStyle.href='report-room.css';document.head.appendChild(reportStyle);
 const menu=document.querySelector('.menu-toggle'),nav=document.querySelector('#global-nav');
 if(menu&&nav){menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',open);menu.textContent=open?'閉じる':'選單'});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');nav.setAttribute('aria-expanded','false');menu.textContent='選單'}))}
 const updated=document.querySelector('#last-updated');if(updated){const d=new Date();updated.textContent=`最終更新：帝國暦 ${d.getFullYear()}.${String(d.getMonth()+1).padStart(2,'0')}.${String(d.getDate()).padStart(2,'0')}`}
 const tabs=[...document.querySelectorAll('.god-tab')],panels=[...document.querySelectorAll('.god-panel')];tabs.forEach(tab=>tab.addEventListener('click',()=>{const season=tab.dataset.season;tabs.forEach(t=>t.classList.toggle('active',t===tab));panels.forEach(p=>p.classList.toggle('active',p.id===`panel-${season}`))}));
 const modal=document.querySelector('#archive-modal'),open=document.querySelector('#archive-open'),close=document.querySelector('#archive-close'),form=document.querySelector('#archive-form'),input=document.querySelector('#archive-password'),content=document.querySelector('#archive-content'),error=document.querySelector('#archive-error');
 const show=()=>{modal.classList.add('open');modal.setAttribute('aria-hidden','false');setTimeout(()=>input.focus(),50)},hide=()=>{modal.classList.remove('open');modal.setAttribute('aria-hidden','true')};
 if(open)open.addEventListener('click',show);if(close)close.addEventListener('click',hide);if(modal)modal.addEventListener('click',e=>{if(e.target===modal)hide()});
 const revealArchive=()=>{content.classList.add('unlocked','visible');content.innerHTML=`<div class="archive-document"><div class="archive-stamp">機密指定 / CONFIDENTIAL</div><p class="eyebrow">四季廳・内部記録　ARCHIVE 17-S</p><h3>四季廳異常記録　第一号</h3><p class="archive-meta">件名：春季観測について<br>記録日：帝國暦 237年 04月12日<br>取扱：保全課・春局</p><hr><p>本記録は、春季現人神・花葉雛菊に関する定例観測記録である。</p><p>現時点において、春季神性の巡行は正常。生命促進作用にも顕著な異常は認められない。</p><p>――以上。</p><div class="archive-note"><strong>【追記】</strong><br>上記記録には、旧記録との照合時に不整合が確認された。</div><div class="archive-redacted">████████████████████████<br>████　該当箇所は閲覧制限　████<br>████████████████████████</div><p class="archive-clue"><span>内部備考：</span><br>「春は――無事、此処に、おります」<br><small>※この文言は、現在の公式資料にのみ存在する。</small></p><button type="button" class="archive-next" id="archive-next">次の記録を閲覧する　→</button><div id="archive-next-record" hidden><hr><p class="eyebrow">ARCHIVE 17-S / SUPPLEMENT</p><h4>照合記録・欠落部分</h4><p>帝國暦 232年以前の春季記録を検索したところ、現存する資料の一部に<strong>「花葉雛菊」の記載が存在しない期間</strong>が確認された。</p><p>しかし、同期間の四季巡行表には「春・正常」と記録されている。</p><p class="archive-warning">【警告】<br>春が存在しなかったのか。<br>それとも――存在していたことを、誰かが記録から消したのか。</p><p class="archive-end">記録終端。<br><span>次回閲覧には別途認証を要する。</span></p></div></div>`;const next=document.querySelector('#archive-next'),record=document.querySelector('#archive-next-record');if(next&&record)next.addEventListener('click',()=>{record.hidden=false;next.hidden=true;record.scrollIntoView({behavior:'smooth',block:'nearest'})})};
 if(form)form.addEventListener('submit',e=>{e.preventDefault();const value=input.value.trim();const key=value.normalize('NFKC').replace(/\s+/g,' ').trim().toLowerCase();const accepted=['雛菊','花葉雛菊','春','四季を絶やすこと','四時を絶やすこと勿れ','hinagiku','kayo hinagiku','kayohinagiku','hanaba hinagiku','hanaba-hinagiku','spring','four seasons','preserve the four seasons','do not let the four seasons cease','do not let the four seasons perish'];const acceptedKeys=accepted.map(v=>v.normalize('NFKC').replace(/\s+/g,' ').trim().toLowerCase());if(acceptedKeys.includes(key)){revealArchive();error.textContent='認証成功。機密資料への閲覧権限を確認しました。'}else{content.classList.remove('unlocked','visible');content.innerHTML='';error.textContent='認証失敗。認証キーワードを確認してください。'}});
 const contact=document.querySelector('#contact');if(contact){const entry=document.createElement('div');entry.className='report-entry';entry.innerHTML=`<button type="button" id="report-open">違法資料を投稿・通報する</button><small>現人神の神性を利用した違法行為、不法資料等を確認した場合は、下記より御通報ください。</small>`;contact.querySelector('.content-width')?.appendChild(entry)}
 const reportModal=document.createElement('div');reportModal.className='report-modal';reportModal.id='report-modal';reportModal.setAttribute('aria-hidden','true');reportModal.innerHTML=`<div class="report-box" role="dialog" aria-modal="true" aria-labelledby="report-title"><button type="button" class="report-close" id="report-close" aria-label="閉じる">×</button><span class="eyebrow">SHIKI AGENCY / REPORT DESK</span><h2 id="report-title">違法資料・不正利用 通報窓口</h2><p>現人神の神性を利用した違法行為、または不正な資料を確認した場合は、内容を記載して御通報ください。</p><form class="report-form" id="report-form"><label>資料種別<select id="report-type"><option>現人神の神性を利用した資料</option><option>四季廳関係の違法資料</option><option>不正な公文書・記録</option><option>その他</option></select></label><label>件名<input id="report-subject" required maxlength="80" placeholder="例：春季旧記録について"></label><label>資料・事象の内容<textarea id="report-body" required maxlength="1200" placeholder="確認した資料や事象の概要を御記入ください。"></textarea></label><button class="report-submit" type="submit">通報を提出する</button></form><div id="report-result" class="report-result" hidden></div></div>`;document.body.appendChild(reportModal);
 const reportOpen=document.querySelector('#report-open'),reportClose=document.querySelector('#report-close'),reportForm=document.querySelector('#report-form'),reportResult=document.querySelector('#report-result');
 const openReport=()=>{reportModal.classList.add('open');reportModal.setAttribute('aria-hidden','false');setTimeout(()=>document.querySelector('#report-subject')?.focus(),50)};const closeReport=()=>{reportModal.classList.remove('open');reportModal.setAttribute('aria-hidden','true')};
 if(reportOpen)reportOpen.addEventListener('click',openReport);if(reportClose)reportClose.addEventListener('click',closeReport);reportModal.addEventListener('click',e=>{if(e.target===reportModal)closeReport()});
 if(reportForm)reportForm.addEventListener('submit',e=>{e.preventDefault();const subject=document.querySelector('#report-subject').value.trim();const type=document.querySelector('#report-type').value;const ref=`SHIKI-${new Date().getFullYear()}-${String(Date.now()).slice(-6)}`;reportResult.hidden=false;reportResult.innerHTML=`<div class="report-pass">通報を受理しました。</div><p>受付番号：<strong>${ref}</strong></p><div class="report-file">資料種別：${type}<br>件名：${subject}</div><p>本件は<strong>四季廳長官室</strong>への回付対象として登録されました。</p><a class="report-enter" id="report-enter" href="chief-office.html">長官室へ通される　→</a>`;const enter=document.querySelector('#report-enter');enter.href=`chief-office.html?ref=${encodeURIComponent(ref)}&subject=${encodeURIComponent(subject)}`;reportForm.querySelector('.report-submit').disabled=true});
 const deityDetails={spring:{season:'SPRING',title:'春季現人神',name:'花葉 雛菊',age:'18歳',divinity:'生命促進',status:'春の現人神',guard:'花葉 さくら',department:'保全課・春局',duties:'春季の巡行、公的祭祀、生命促進に関する神祇行政への協力。帝國各地の春季行事・神域との調整を担います。',ritual:'春季奉告祭、芽吹きの儀、春季巡行祭ほか。',notice:'春季現人神に関する公的情報は、四季廳官報および春局発表を御確認ください。'},summer:{season:'SUMMER',title:'夏季現人神',name:'葉桜 瑠璃',age:'18歳',divinity:'生命使役',status:'夏の現人神',guard:'葉桜 あやめ',department:'保全課・夏局',duties:'夏季の巡行、公的祭祀、生命使役に関する神祇行政への協力。夏季の神域・祭事に関する公務を担います。',ritual:'夏季奉告祭、盛夏神事、夏季巡行祭ほか。',notice:'夏季現人神に関する公的情報は、四季廳官報および夏局発表を御確認ください。'},autumn:{season:'AUTUMN',title:'秋季現人神',name:'祝月 杏莉',age:'7歳',divinity:'生命腐敗',status:'秋の現人神',guard:'阿佐美 竜胆',department:'保全課・秋局',duties:'秋季の巡行、公的祭祀、生命腐敗に関する神祇行政への協力。収穫・循環に関する祭祀および神域行政を担います。',ritual:'秋季奉告祭、収穫祭、秋季巡行祭ほか。',notice:'秋季現人神に関する公的情報は、四季廳官報および秋局発表を御確認ください。'},winter:{season:'WINTER',title:'冬季現人神',name:'森 林太郎',age:'32歳',divinity:'生命凍結',status:'冬の現人神／日ノ本帝國皇太子・薄氷宮幸仁',guard:'雪柳 残雪',department:'保全課・冬局',duties:'冬季の巡行、公的祭祀、生命凍結に関する神祇行政への協力。冬季の国家行事および宮内関係公務にも携わります。',ritual:'冬季奉告祭、年越神事、冬季巡行祭ほか。',notice:'冬季現人神に関する公的情報は、四季廳官報、冬局および宮内関係発表を御確認ください。'}};
 const deityStyle=document.createElement('style');deityStyle.textContent=`.deity-detail-modal{position:fixed;inset:0;z-index:9999;display:none;align-items:center;justify-content:center;padding:24px;background:rgba(7,8,10,.82);backdrop-filter:blur(4px)}.deity-detail-modal.open{display:flex}.deity-detail-panel{position:relative;width:min(920px,94vw);max-height:88vh;overflow:auto;background:#eee9df;color:#191715;border:1px solid rgba(112,24,30,.55);box-shadow:0 24px 80px rgba(0,0,0,.5);padding:42px}.deity-detail-close{position:absolute;top:12px;right:16px;border:0;background:none;font-size:30px;cursor:pointer;color:#4a1519}.deity-detail-kicker{letter-spacing:.18em;font-size:11px;color:#7a2028}.deity-detail-name{font-family:serif;font-size:clamp(30px,5vw,52px);margin:8px 0 4px}.deity-detail-title{font-size:13px;letter-spacing:.16em;color:#7a2028;margin-bottom:28px}.deity-detail-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));border-top:1px solid #aaa096}.deity-detail-grid div{padding:15px 12px;border-bottom:1px solid #c8c0b5}.deity-detail-grid dt{font-size:11px;letter-spacing:.12em;color:#776d65;margin-bottom:5px}.deity-detail-grid dd{margin:0;font-family:serif;font-size:17px}.deity-detail-block{margin-top:26px;padding-top:18px;border-top:1px solid #aaa096}.deity-detail-block h4{margin:0 0 8px;font-size:14px;letter-spacing:.12em;color:#7a2028}.deity-detail-block p{margin:0;line-height:1.9}.god-tab{cursor:pointer}.god-tab::after{content:'詳 細';display:block;font-size:9px;letter-spacing:.16em;opacity:.65;margin-top:3px}@media(max-width:650px){.deity-detail-panel{padding:28px 20px}.deity-detail-grid{grid-template-columns:1fr}.deity-detail-name{font-size:34px}}`;document.head.appendChild(deityStyle);
 const deityModal=document.createElement('div');deityModal.className='deity-detail-modal';deityModal.id='deity-detail-modal';deityModal.setAttribute('aria-hidden','true');deityModal.innerHTML='<div class="deity-detail-panel" role="dialog" aria-modal="true" aria-labelledby="deity-detail-name"><button type="button" class="deity-detail-close" id="deity-detail-close" aria-label="閉じる">×</button><span class="deity-detail-kicker" id="deity-detail-kicker"></span><h2 class="deity-detail-name" id="deity-detail-name"></h2><div class="deity-detail-title" id="deity-detail-title"></div><dl class="deity-detail-grid"><div><dt>御名</dt><dd id="deity-name-value"></dd></div><div><dt>神性</dt><dd id="deity-divinity"></dd></div><div><dt>年齢</dt><dd id="deity-age"></dd></div><div><dt>現在の御身分</dt><dd id="deity-status"></dd></div><div><dt>専属護衛官</dt><dd id="deity-guard"></dd></div><div><dt>所属局</dt><dd id="deity-department"></dd></div></dl><div class="deity-detail-block"><h4>公務</h4><p id="deity-duties"></p></div><div class="deity-detail-block"><h4>祭祀</h4><p id="deity-ritual"></p></div><div class="deity-detail-block"><h4>公式発表</h4><p id="deity-notice"></p></div></div>';document.body.appendChild(deityModal);
 const detailClose=document.querySelector('#deity-detail-close');const closeDeity=()=>{deityModal.classList.remove('open');deityModal.setAttribute('aria-hidden','true')};if(detailClose)detailClose.addEventListener('click',closeDeity);deityModal.addEventListener('click',e=>{if(e.target===deityModal)closeDeity()});
 tabs.forEach(tab=>tab.addEventListener('click',()=>{const d=deityDetails[tab.dataset.season];if(!d)return;document.querySelector('#deity-detail-kicker').textContent=`${d.season} / FOUR DIVINE SEASONS`;document.querySelector('#deity-detail-name').textContent=d.name;document.querySelector('#deity-detail-title').textContent=d.title;document.querySelector('#deity-name-value').textContent=d.name;document.querySelector('#deity-divinity').textContent=d.divinity;document.querySelector('#deity-age').textContent=d.age;document.querySelector('#deity-status').textContent=d.status;document.querySelector('#deity-guard').textContent=d.guard;document.querySelector('#deity-department').textContent=d.department;document.querySelector('#deity-duties').textContent=d.duties;document.querySelector('#deity-ritual').textContent=d.ritual;document.querySelector('#deity-notice').textContent=d.notice;deityModal.classList.add('open');deityModal.setAttribute('aria-hidden','false') }));
 document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(reportModal.classList.contains('open'))closeReport();else if(modal.classList.contains('open'))hide();else if(deityModal.classList.contains('open'))closeDeity()}});
 document.querySelectorAll('.sub-departments h3').forEach(el=>{
   let text=el.textContent.replace(/\s+/g,' ').trim();
   if(text.includes('担当：加州 清光')) text=text.replace('担当：加州 清光','課長：加州 稀世光');
   text=text.replace(/課長：雪柳(?: 浪雪)+/,'課長：雪柳 浪雪');
   if(text.includes('課長：雪柳')&&!text.includes('課長：雪柳 浪雪')) text=text.replace('課長：雪柳','課長：雪柳 浪雪');
   if(text.includes('課長：南海太郎朝尊')) text=text.replace('課長：南海太郎朝尊','課長：南海 美哉臣');
   el.textContent=text;
 });
});
